stages:
  - test
  - deploy


testing:
  stage: test
  image: ${CI_REGISTRY}/devops/infra/ci-cd-helpers:deploy
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  script:
    - apk update && apk add openssh-client
    - apk add --no-cache ansible
    - eval $(ssh-agent) && echo "$SSH_ID_RSA" | ssh-add -
    #- install -m 600 $SSH_KNOWN_HOSTS /etc/ssh/ssh_known_hosts
    - export ANSIBLE_SSH_ARGS="-o StrictHostKeyChecking=no -i $CI_PROJECT_DIR/key/ansible-abb"
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - chmod 600 $CI_PROJECT_DIR/key/ansible-abb
    - ansible -m ping -i hosts1 all -c paramiko -vvv
  tags:
  - tests

deploy-to-swarm:
  stage: deploy
  image: ${CI_REGISTRY}/devops/infra/ci-cd-helpers:deploy
  before_script:
    - apk update && apk add openssh-client
    - apk add --no-cache ansible
    - eval $(ssh-agent) && echo "$SSH_ID_RSA" | ssh-add -
    - export ANSIBLE_SSH_ARGS="-o StrictHostKeyChecking=no -i $CI_PROJECT_DIR/key/ansible-abb"
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - chmod 600 $CI_PROJECT_DIR/key/ansible-abb
  script:
    - ansible-playbook -i hosts1 playbook.yaml 
  when: manual

