---
- name: Ensure Docker is installed
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
        force_apt_get: yes

    - name: Ensure Docker service is enabled and started
      service:
        name: docker
        state: started
        enabled: yes

